#!/bin/bash
import threading,requests


array_url =["https://api.github.com","http://bilgisayar.mu.edu.tr/","https://www.python.org/","http://akrepnalan.com/ceng2034","https://github.com/caesarsalad/wow"]

def request(url):

          res=requests.get(url)
          res_code =res.status_code

          if(200<=res_code<=300):
                   print(url +" URL is valid")
          else:
                   print(url +" URL is invalid")

for i in range(0,5):

        thread1 =threading.Thread(target=request,args=(array_url[i],))
        thread1.start()
